export const inputCars = [
    {
        labelName: 'Brand',
        typeInput: 'text',
        placeholder: 'Introduce the brand',
        name: 'brand',
        iconDefault: 'fas fa-car',
    },
    {
        labelName: 'Model',
        typeInput: 'text',
        placeholder: 'Introduce the model',
        name: 'model',
        iconDefault: 'fas fa-car',
    },
    {
        labelName: 'Year',
        typeInput: 'text',
        placeholder: 'Introduce the year',
        name: 'year',
        iconDefault: 'fas fa-calendar',
    },
    {
        labelName: 'Kilometers',
        typeInput: 'text',
        placeholder: 'Introduce the kilometers',
        name: 'kilometers',
        iconDefault: 'fas fa-solid fa-sun',
    },
    {
        labelName: 'Color',
        typeInput: 'text',
        placeholder: 'Introduce the color',
        name: 'color',
        iconDefault: 'fas fa-brush',
    },
    {
        labelName: 'Passangers',
        typeInput: 'text',
        placeholder: 'Introduce the number of passangers',
        name: 'passangers',
        iconDefault: 'fas fa-users',
    },
    {
        labelName: 'Test',
        typeInput: 'radio',
        value: '2',
        name: 'type_transmision',
    },
    {
        labelName: '',
        typeInput: 'radio',
        value: '1',
        name: 'type_transmision',
    },
];
